In [70]:
import pandas as pd
import numpy as np
import importlib
import re
import med_utils
importlib.reload(med_utils)

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [71]:
AIBL_df = pd.read_excel('../raw_datasets/AIBL/AIBL_2023.xlsx')

In [72]:
AIBL_df.columns

Index(['AIBL ID', 'Collection', 'Enrolment', 'Recruitment', 'Actigraph.Light',
       'Actigraph.Medium', 'Actigraph.Hard', 'Actigraph.Very Hard',
       'Actigraph.Avg Counts', 'Actigraph.Peak Counts',
       ...
       'ShortIq.FollowingStoryBook', 'ShortIq.MakingDecisions',
       'ShortIq.HandlingMoney', 'ShortIq.HandingFinancial',
       'ShortIq.HandlingEveryday', 'ShortIq.UsingIntelligence',
       'ShortIq.TotalScore', 'FollowUp.HighCholesterolDiagnosis',
       'FollowUp.HypertensionDiagnosis', 'FollowUp.DiabetesDiagnosis'],
      dtype='str', length=1400)

In [73]:
AIBL_df_clean = med_utils.clean_dataframe_advanced(AIBL_df, missing_values=[" "], threshold=1, drop_rows_threshold=None, verbose=True)
AIBL_df_clean['Demographic.YearMonthOfBirth']=AIBL_df_clean['Demographic.YearMonthOfBirth'].astype(str) + '01'
AIBL_df_clean['Demographic.YearMonthOfBirth'] = pd.to_datetime(AIBL_df_clean['Demographic.YearMonthOfBirth'], format='%Y%m%d')
AIBL_df_clean[['Demographic.YearMonthOfBirth']] = AIBL_df_clean.groupby('AIBL ID')[['Demographic.YearMonthOfBirth']].transform(lambda x: x.ffill().bfill())
AIBL_df_clean['Progress Summary.Date of NP assessment'] = pd.to_datetime(AIBL_df_clean['Progress Summary.Date of NP assessment'], format='%d/%m/%Y')
AIBL_df_clean['Age'] = round((AIBL_df_clean['Progress Summary.Date of NP assessment'] - AIBL_df_clean['Demographic.YearMonthOfBirth']).dt.days / 365, 2)
print("Missing AIBL Age records:", AIBL_df_clean["Age"].isna().sum())
AIBL_df_clean = med_utils.fill_missing_ages_AIBL(AIBL_df_clean, n_jobs = 11)
print("Missing AIBL Age records after fill given assumption of 18 month of AIBL visits:", AIBL_df_clean["Age"].isna().sum())

Original shape: (37818, 1400)
Missing values replaced: [' ']
Columns dropped: 0 ([])
Final shape: (37818, 1400)

/var/folders/1k/gxqd2vls7rz_4lbm2q2_0cy80000gn/T/ipykernel_98147/3195128985.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  AIBL_df_clean['Age'] = round((AIBL_df_clean['Progress Summary.Date of NP assessment'] - AIBL_df_clean['Demographic.YearMonthOfBirth']).dt.days / 365, 2)

Missing AIBL Age records: 27659
Missing AIBL Age records after fill given assumption of 18 month of AIBL visits: 3619

In [74]:
# drop rows with AIBL Age or Neuropsych.Simple Classification (status) missing
mask_missing = AIBL_df_clean["Age"].isna() | AIBL_df_clean["Neuropsych.Simple Classification"].isna()
print(f"Rows with missing Age or status to drop: {mask_missing.sum()}")
AIBL_df_clean = AIBL_df_clean.loc[~mask_missing].copy()
print(f"After dropping missings: {len(AIBL_df_clean)}")

Rows with missing Age or status to drop: 13220
After dropping missings: 24598

In [75]:
medication_columns = [col for col in AIBL_df_clean.columns if col.startswith("Medical History.Name of medication")]
disease_map = {
    'CVD': ['Medical History.Hypertension', 'Medical History.Heart Attack', 'Medical History.Stroke'],                              # CVD = Hypertension+ Heart attack+stroke
    'Endocrine': ['Medical History.Diabetes', 'Medical History.Thyroid/Parathyroid Disease', 'Medical History.HighCholesterol'],    # endocrine = Diabetes + Thyroid + high cholesterol
    'Psychiatric': ['Medical History.Anxiety',  'Medical History.Depression']                                                     # Psychiatric = Anxiety + Depression
}
disease_columns = [col for cols in disease_map.values() for col in cols]
disease_columns_rename = list(disease_map.keys())
AIBL_df_selected = med_utils.rename_and_select_columns(AIBL_df_clean, "../raw_datasets/naming_convension.xlsx", "AIBL", "New_Name", extra_cols=medication_columns+disease_columns)

In [76]:
AIBL_df_selected = med_utils.create_disease_variables(AIBL_df_selected, disease_map)

In [77]:
print("The dimension of the selected AIBL dataframe is:", AIBL_df_selected.shape, "with", AIBL_df_selected['id'].nunique(), "unique participants.")
AIBL_df_selected = AIBL_df_selected[AIBL_df_selected['status'].isin(['HC', 'MCI', 'AD'])]
AIBL_df_selected['sex'] = AIBL_df_selected['sex'].map({"Male":0 , 'Female':1})
AIBL_df_selected['APOE4'] = AIBL_df_selected['APOE4'].apply(lambda x: 1 if isinstance(x, str) and 'E4' in x else 0)

print("The dimension of the selected AIBL dataframe after drop unrelated with AD is:", AIBL_df_selected.shape, "with", AIBL_df_selected['id'].nunique(), "unique participants.")
AIBL_df_selected = med_utils.clean_status_and_demos(AIBL_df_selected)
AIBL_df_selected = AIBL_df_selected.dropna(subset=['status'])
AIBL_df_selected = AIBL_df_selected[~(AIBL_df_selected['MMSE'].isna() & AIBL_df_selected['CDR'].isna())]
AIBL_df_selected = AIBL_df_selected.reset_index(drop=True)
print("The dimension of the selected AIBL dataframe is:", AIBL_df_selected.shape, "with", AIBL_df_selected['id'].nunique(), "unique participants.")
med_df=AIBL_df_selected[medication_columns]
selected_columns = AIBL_df_selected.columns.tolist()

The dimension of the selected AIBL dataframe is: (24598, 42) with 2790 unique participants.
The dimension of the selected AIBL dataframe after drop unrelated with AD is: (9503, 42) with 2503 unique participants.
Filled 0 missing status records; columns forward/back filled: ['sex', 'edu', 'APOE4']
The dimension of the selected AIBL dataframe is: (9487, 42) with 2502 unique participants.

### angiotensin-converting enzyme inhibitors (ACEi)

In [78]:
acei_files = pd.read_excel('../raw_datasets/names.xlsx', sheet_name='ACEi')
acei_names = list(set(acei_files['Drug_name'].dropna()).union(acei_files['Brand_name'].dropna()))

In [79]:
acei_matched_values = med_utils.get_matched_values(med_df, acei_names)

In [80]:
acei_matched_values

['lisimopril',
 'Fe',
 'Ramipril',
 'Perindopril Erbumine',
 '30 Perindopril',
 'MONOPRIL',
 'perindopril / indapamide',
 'ACCUPRIL',
 'perindopril erbumine',
 'Enalapril Maleate',
 'QUINAPRIL',
 'Lisiuopril',
 'Filpril (Quinapril)',
 'rammipril',
 'perindo',
 'Tritace (Ramipril)',
 'Captopril Tablets',
 'RAMIPRIL',
 'MONOPRIEL',
 'Fosinopril',
 'Quinapril',
 'Rampril',
 'perendopril',
 'CM-Perindopril',
 'Enalapril',
 'Zestril',
 'Coversyl, perindopril, arginine',
 'LISINOPRIL/LISODOR',
 'accupril',
 'ENALAPRIL',
 'Perindo',
 'Accupril',
 'RamiprilWinthrop',
 'zestril',
 'Perindapril',
 'perindopril',
 'Indapam/perindopril',
 'Coversyl Plus (Perindopril, indapamde-hemhydrate',
 'PERINDOPRIL',
 'Gopten (trandolapril)',
 'Ramipril ( will change to Atacand soon)',
 'Perindopril',
 'Monopril',
 'Enalapril Acetec',
 'Bace',
 'Rampipril',
 'ACE',
 'ramipril',
 'Ramipril sz',
 'Perindopril/Indapamide',
 'Azep',
 'Lisinopril',
 'perindopril/indapamide',
 'Perindopril arginine',
 'Penindopril',
 'Tryzan Ramipril',
 'Perendopril',
 'PRINIVIL',
 'rampril',
 'Capoten',
 'monopril',
 'CAPOTEN']

In [81]:
values_to_drop_aceinames = {'Azep', 'Fe', 'Bace', }
acei_matched_values = [x for x in acei_matched_values if x not in values_to_drop_aceinames]

In [82]:
acei_all = med_utils.medication_all_timepoints(
    AIBL_df_selected, acei_matched_values, medication_columns, selected_columns,
    id_col="id", visit_col="visit_no"
)
# acei_all.to_csv("../preprocessed_data/AIBL/acei_all_results_AIBL_missing.csv",index=False)

### angiotensin receptor blockers (ARBs)

In [83]:
arb_files = pd.read_excel('../raw_datasets/names.xlsx', sheet_name='ARB')
arb_names = list(set(arb_files['Drug_name'].dropna()).union(arb_files['Brand_name'].dropna()))

In [84]:
arb_matched_values = med_utils.get_matched_values(med_df, arb_names)

In [85]:
arb_matched_values

['valsartan',
 'Atacand',
 'Valsartan',
 'Micardis Plus',
 'Tolmisartan',
 'telmisartant',
 'Olmetec Plus',
 'Exforge (anlodifine/valsartan)',
 'Avapro HCT 300/12.5',
 'Antacand',
 'AVAPRO HCT',
 'Exforge (amlodipine/valsartan)',
 'Avapro HCT (150/12.5 mg)',
 'Telmisartan/Micardis',
 'Irbestartan',
 'IRBESARTEN',
 'olmetec',
 'micardis',
 'irbesartan HCT2',
 'Micardis-80',
 'Irbesarten',
 'olmetec plus',
 'VE',
 'Atcand',
 'avapro HCT',
 'Irbesartan/hydrochlorothiazide',
 'valsartanl',
 'Avapro HCT (150/12.5)',
 'AVAPRO/HCT',
 'Atacand plus 32/12.5',
 'OLMESARTAN',
 'co-diovan',
 'Valsartan amlodipine',
 'irbesartan',
 'valsartan/hydrochlorothiazide',
 'Co-diovan',
 'Candesartan',
 'Olmestartan',
 'Irbesartan HCT',
 'Micardis plus',
 'Atacand Plus 16/12.5',
 'diovan valsartin',
 'Telmisartan Amlodipine',
 'olmesarton',
 'Micardis Plus 80/12.5',
 'Olmesartan/HCT',
 'Valsartan hydrochlorothiazide',
 'co diovan',
 'telmisartan',
 'Olmesartan amlodipine',
 'Atacand plus',
 'Atacand Plus',
 'Atacan',
 'candesartan',
 'attacand',
 'Ramipril ( will change to Atacand soon)',
 'Atacand Plus 16/12',
 'Irbersatan',
 'candestartan',
 'Olmtec',
 'Avapro HCT 300mg/12.5mg',
 'Karvezide (150 mg irbesartan/12.5 mg hydrochlorothiazide)',
 'APO-Olmesartan',
 'Avapro (Blood pressure)',
 'MICARDIS PLUS',
 'micardis plus',
 'Teveten',
 'Olmesartan',
 'irbestartan',
 'IRBESARTAN/HYDROCHLORTHIAZIDE',
 'Diovan',
 'diovan',
 'Olmetec',
 'Ibestartan',
 'Telmisartan/Hydrochlorothiazide',
 'ATACAN',
 'Attacand',
 'Telmisartan HCTZ 40/12.5',
 'Avapro 150mg/12.50mg',
 'Candesartan Aspen',
 'ATACAND Plus',
 'irberartan',
 'Micardis plus 80/12.5',
 'Avapro',
 'ATACAND',
 'olmosartan',
 'micardis tablet',
 'olmesartan',
 'Telmisartan',
 'COZAR',
 'AVAPRO',
 'Irbestarta',
 'Valsartan/Hydrochlorothiazide',
 'MICARDIS Tab',
 'atacand +',
 'avarpro',
 'AMLODIPINE-VALSARTAN',
 'CO-DIOVAN',
 'Apo-Candesartan',
 'Avapro HCT  Hydrochlorothiazide',
 'Telmisartan/HCT sandoz',
 'OLMESARTON',
 'Telmisartan/amcodipine',
 'avapro-hct',
 'atacand',
 'antacand',
 'Irbesarton',
 'Avapro150',
 'Actacand',
 'TEVETEN PLUS',
 'Apo-telmisartan',
 'Apo-Olmesartan',
 'Avapro HCT   Irbesartan',
 'Olmetec (olmesaran medoxomil)',
 'Micardis',
 'Valsartan/Amlodipine',
 'IRBESARTAN',
 'Candezartan',
 'avapro',
 'avapro hct',
 'Irbesartan',
 'ATACAND PLUS',
 'micadis',
 'Avapro HCT',
 'MICARDIS',
 'Candesartan cilexetil',
 'OLMETEC',
 'ado- candesartan']

In [86]:
values_to_drop_arbnames = {'VE'}
arb_matched_values = [x for x in arb_matched_values if x not in values_to_drop_arbnames]

In [87]:
arb_all = med_utils.medication_all_timepoints(
    AIBL_df_selected, arb_matched_values, medication_columns, selected_columns,
    id_col="id", visit_col="visit_no"
)
# arb_all.to_csv("../preprocessed_data/AIBL/arb_all_results_AIBL_missing.csv",index=False)

### Beta Blocker

In [88]:
beta_blockers_files = pd.read_excel('../raw_datasets/names.xlsx', sheet_name='beta_blockers')
beta_blockers_names = list(set(beta_blockers_files['Drug_name'].dropna()).union(beta_blockers_files['Brand_name'].dropna()))

In [89]:
beta_blockers_matched_values = med_utils.get_matched_values(med_df, beta_blockers_names)

In [90]:
beta_blockers_matched_values

['sotalol',
 'Meloprolol',
 'Sotalol h/chloride',
 'Metopropol',
 'Timolol',
 'ATENOLOL',
 'Bisoprolol Fumarate',
 'atenalol',
 'metroprolol',
 'Metoprolol tartrate (sz)',
 'metoprolol',
 'Carvedilol',
 'METOPROLOL',
 'toprol',
 'carvediol',
 'Atenol',
 'propanolol',
 'Metoprolol',
 'propraholol',
 'propranolol',
 'METROPROLOL',
 'timolol',
 'Sotalol Hydrochloride',
 'tenaormin',
 'Betaloc (Metoprolol tartrate)',
 'Propranolol',
 'Sotalol',
 'METOPOLOL',
 'Timolol eye-drops 0.5%',
 'Propanolol',
 'Meteprolol',
 'metropolol',
 'tenormin',
 'Metroprolol',
 'Betaloc (Beta blocker)',
 'DILATREND (Carvedilol)',
 'Timolol Eye drops',
 'atenolol',
 'Metoprolol Tart',
 'metoprolol  AN',
 'metoprocol',
 'Apo metoprolol',
 'TERNORMIN',
 'Xalacom latanoprost timolol',
 'metaprolol',
 'ACE',
 'METROPOLOL',
 'Inderal',
 'ATENALOL',
 'SOTALOL',
 'Nebivolol',
 'Metoprolo',
 'Tenormin',
 'METOPROLOL TARTRATE',
 'Metoprolol Tartrate',
 'carvedilol',
 'Toprol XL',
 'VE',
 'metopolol',
 'nebivolol',
 'Sotalol hydrocholride',
 'toprol-XL',
 'Atenolol',
 'Metropolol',
 'INDERAL',
 'METOPROLOL (Minax)',
 'Bisoprolol',
 'Tenorimin',
 'bisoprodol',
 'metopropol',
 'Tenormin Noten Tensig Atehexal',
 'Carvedilol (Dicarz)',
 'Apo-Metoprolol']

In [91]:
values_to_drop_BetaBlknames = {'ACE', 'VE'}
beta_blockers_matched_values = [x for x in beta_blockers_matched_values if x not in values_to_drop_BetaBlknames]

In [92]:
beta_blockers_all = med_utils.medication_all_timepoints(
    AIBL_df_selected, beta_blockers_matched_values, medication_columns, selected_columns,
    id_col="id", visit_col="visit_no"
)
# beta_blockers_all.to_csv("../preprocessed_data/AIBL/beta_blockers_all_results_AIBL_missing.csv",index=False)

### Calcium Channel Blockers

In [93]:
Ca_channel_blockers_files = pd.read_excel('../raw_datasets/names.xlsx', sheet_name='Ca_channel_blockers')
Ca_channel_blockers_names = list(set(Ca_channel_blockers_files['Drug_name'].dropna()).union(Ca_channel_blockers_files['Brand_name'].dropna()))

In [94]:
Ca_channel_blockers_matched_values = med_utils.get_matched_values(med_df, Ca_channel_blockers_names)

In [95]:
Ca_channel_blockers_matched_values

['Lercandipine',
 'Amrodipine',
 'NAC',
 'amlo',
 'Norvasc',
 'CARDIZEM',
 'AMLODOPINE',
 'Exforge (amlodipine/valsartan)',
 'AMLO',
 'lercanidipone',
 'ZANIDIP',
 'LERCANIDIPINE/HYDROCHLORIDE',
 'VE',
 'Zanidip, 20 ml',
 'Nifedipine Adefin XL',
 'Calcium',
 'Lercanidipine-HCI',
 'tazac',
 'Fe',
 'LERCAN',
 'norvasc',
 'calcium +',
 'Valsartan amlodipine',
 'Lercanidipine Hydrochloride',
 'nifedipine',
 'Verapamil',
 'Telmisartan Amlodipine',
 'Tazac',
 'lercanidipine',
 'Lercanidipine',
 'Folodipine',
 'Olmesartan amlodipine',
 'Cardizem',
 'verapamil',
 'amlodopine',
 'Amiodipine',
 'plendiler',
 'adalat',
 'lercandipine',
 'lerconidipine',
 'almodipine',
 'diltiazem',
 'CALCIUM',
 'cardizem',
 'Diltiazem',
 'Adalat',
 'PLENDIL ER',
 'Amlodipine',
 'Zanidip',
 'Apo-amlodipine',
 'AMLODAPINE',
 'Amlodipine Besylate',
 'Nifedipine',
 'FELODIPINE',
 'Plendil',
 'NORVASC',
 'APO-AMLODIPINE',
 'AMLODIPINE-VALSARTAN',
 'ZANIDIP/ZIRCOL',
 'calcium',
 'apo- lercanidipine',
 'PLENDIL',
 'amlodipine Hi Prex',
 'Pritor/Amlodipine',
 'Felodepine',
 'Amlodopine',
 'Norvac',
 'Amlodipine/Atorvastatin',
 'cardizem cd',
 'AMLODIPINE',
 'Amolodipine',
 'lercan',
 'ADALAT',
 'Zandip',
 'Valsartan/Amlodipine',
 'zanidip',
 'Felodipine ER',
 'Amlo',
 'Novasc',
 'felodipine',
 'Felodipine',
 'Norvascc',
 'Lercanidipine (Zircol)',
 'nitedipine',
 'amlodipine',
 'Plendil ER']

In [96]:
values_to_drop_ccbnames = {'calcium +', 'Calcium', 'calcium', 'CALCIUM', 'Fe', 'VE', 'NAC',}
Ca_channel_blockers_matched_values = [x for x in Ca_channel_blockers_matched_values if x not in values_to_drop_ccbnames]

In [97]:
Ca_channel_blockers_all = med_utils.medication_all_timepoints(
    AIBL_df_selected, Ca_channel_blockers_matched_values, medication_columns, selected_columns,
    id_col="id", visit_col="visit_no"
)
# Ca_channel_blockers_all.to_csv("../preprocessed_data/AIBL/Ca_channel_blockers_all_results_AIBL_missing.csv",index=False)

### Diuretics

In [98]:
diuretics_files = pd.read_excel('../raw_datasets/names.xlsx', sheet_name='diuretics')
diuretics_names = list(set(diuretics_files['Drug_name'].dropna()).union(diuretics_files['Brand_name'].dropna()))

In [99]:
diuretics_matched_values = med_utils.get_matched_values(med_df, diuretics_names)

In [100]:
diuretics_matched_values

['Spironolactone',
 'LASIX',
 'aldactone',
 'Chlorthal',
 'Indapamide SR',
 'hydrochlorothiazidie',
 'Hygroton',
 'perindopril / indapamide',
 'Spironolacton',
 'Diuretic',
 'Telmisartan/Hydrochlorothiazide',
 'spirano lactone',
 'valsartan/hydrochlorothiazide',
 'none',
 'iron',
 'hydrochlorothiazide',
 'LASIX-M',
 'lasix',
 'Urex (Furosemide)',
 'IRON',
 'Spiractin (Spironolactose)',
 'hydrchlorothiazide',
 'Furosemide',
 'Spiractin',
 'Pelindopril and Indapamide',
 'furosemide',
 'Spiractin 25',
 'Valsartan hydrochlorothiazide',
 'Natrilix (Indapamide hemihydrate)',
 'lasix M',
 'Spiractin (Aldactone)',
 'spirolactone',
 'indapamide',
 'Iron',
 'indapanmide',
 'ACE',
 'SPIRONOLACTONE',
 'Perindopril/Indapamide',
 'diuretic',
 'pironolactone',
 'INDAPAMIDE',
 'Indapamide',
 'spiractin',
 'perindopril/indapamide',
 'Valsartan/Hydrochlorothiazide',
 'hygroton',
 'Aldactone',
 'Lasix',
 'Hydrochlorothiazide',
 'Irbesartan/hydrochlorothiazide',
 'Potassium',
 'Avapro HCT  Hydrochlorothiazide',
 'Karvezide (150 mg irbesartan/12.5 mg hydrochlorothiazide)']

In [101]:
values_to_drop_diureticsnames = {'Iron', 'Potassium', 'ACE', 'none', 'IRON', 'iron'}
diuretics_matched_values = [x for x in diuretics_matched_values if x not in values_to_drop_diureticsnames]

In [102]:
diuretics_all = med_utils.medication_all_timepoints(
    AIBL_df_selected, diuretics_matched_values, medication_columns, selected_columns,
    id_col="id", visit_col="visit_no"
)
# diuretics_all.to_csv("../preprocessed_data/AIBL/diuretics_all_results_AIBL_missing.csv",index=False)

### statins

In [103]:
statin_files = pd.read_excel('../raw_datasets/names.xlsx', sheet_name='statin')
statin_names = list(set(statin_files['Drug_name'].dropna()).union(statin_files['Brand_name'].dropna()))

In [104]:
statin_matched_values = med_utils.get_matched_values(med_df, statin_names)

In [105]:
statin_matched_values

['rosuvstatin',
 'ezetimibe+ simvastatin',
 'Pravacol',
 'Lipitor??',
 'apo- rosuvastatin',
 'amalodipine vasolate/atorvastatin calcium',
 'Prevastatin',
 'Atorvastatin (lipitor)',
 'atorvostatin',
 'Simuastatin',
 'ATORVASTATIN SANDOZ',
 'Crestor (5mgm)',
 'Liptor',
 'Zocor (simvastatin)',
 'pravastatin',
 'Zocor (Zimvastatin)',
 'Atvastatin',
 'atoruastatin',
 'Lipitor (Atorvastatin)',
 'Lipitor 20mg',
 'Pravarachol',
 'PRAVASTATIN',
 'Atrovastatin',
 'statin',
 'SIMVASTATIN',
 'atorvastin',
 'Fluvastatin',
 'Pravastin',
 'Cretor',
 'Pravastatin Sodium',
 'lescol',
 'Simvarstatin',
 'ZOCOR',
 'Rosuvastatin Apotex',
 'SIMVASTIN',
 'Lipitor',
 'Lipator (Atorvastatin)',
 'Pravachol',
 'Lipitor Atorvastatin',
 'Pravast',
 'Simbastatin',
 'liptor',
 'Crestor (cholesterol)',
 'rosuvostatin',
 'Pravastatin',
 'simvastin',
 'Atoruastatin',
 'crestor',
 'ROSUVASTATIN',
 'Lescol',
 'Apo-Rosuvastatin',
 'LIPITOR tab',
 'Atorvastin',
 'Atarvastatin',
 'pravacol',
 'Rosuvastin',
 'CM-Simvastatin',
 'ASORVASTATIN',
 'Rosuvastation',
 'pravachol',
 'Simvastatin',
 'Lipitopr',
 'rosuvastatin calcium',
 'SIMVAR/ZOCOR/ZIMSTAT',
 'Simvastatin 40',
 'Rosvastatin',
 'Atorvachol/Atorvastatin/Lipitor',
 'risuvastatin',
 'Zocore',
 'Coversyl, rosuvastatin-RBX',
 'CRESTOR',
 'Previous, Lipitor',
 'atorvastatin',
 'Atorvastatin',
 'Atorvastatin (sz)',
 'apo rosuvastatin',
 'ato-atorvastatin',
 'pravastin',
 'zocor',
 'Prava statin',
 'Crestor',
 'lipitor',
 'Simvastin',
 'Rovastatin',
 'Zocor',
 'Rosuvastatin (APO)',
 'Symvastatin',
 'atorvastaten',
 'ATORVASTATIN',
 'Amlodipine/Atorvastatin',
 'Apo-simvastatin',
 'PRAVACHOL',
 'LIPITOR',
 'atrovastatin',
 'simvastatin',
 'Rosuvastatin',
 'Rosulvastatin',
 'Provastatin',
 'rosuvastatin',
 'Apo-atorvastatin',
 'atoravastatin',
 'artovastatin',
 'Ezetimibel Rosuvastatin',
 'rosivastatin',
 'rosuvastin',
 'SEMVASTATIN',
 'SM-Simvastatin',
 'Statin']

In [106]:
values_to_drop_statinnames = {'Iron', 'Potassium', 'ACE', 'none', 'IRON', 'iron'}
statin_matched_values = [x for x in statin_matched_values if x not in values_to_drop_statinnames]

In [107]:
statin_all = med_utils.medication_all_timepoints(
    AIBL_df_selected, statin_matched_values, medication_columns, selected_columns,
    id_col="id", visit_col="visit_no"
)
# statin_all.to_csv("../preprocessed_data/AIBL/statin_all_results_AIBL_missing.csv",index=False)

### metformin

In [108]:
metformin_files = pd.read_excel('../raw_datasets/names.xlsx', sheet_name='metformin')
metformin_names = list(set(metformin_files['Drug_name'].dropna()).union(metformin_files['Brand_name'].dropna()))

In [109]:
metformin_matched_values = med_utils.get_matched_values(med_df, metformin_names)

In [110]:
metformin_matched_values

['DIAFORMIN 500',
 'DIABEX',
 'diabex XD',
 'jardiamet',
 'diaformin xr',
 'diaformin',
 'metformin hydrochloride',
 'Diabex',
 'Metformin HCL',
 'Diabex XR 1000',
 'Diaformin',
 'Metformin',
 'Diaformin Xr',
 'Metformin Hydrochloride',
 'Glucovance',
 'Metex',
 'Jardiamet 5/1000',
 'Formet Aspen',
 'diabex',
 'dianformin',
 'Jardiamet',
 'Diabex XR',
 'Glucohexal',
 'formetaspen',
 'Glucovance (500/5mg)',
 'medformin',
 'METFORMIN',
 'Diaformin XR',
 'metex xr',
 'GLUCOVANCE',
 'Medformin',
 'VE',
 'DIAFORMIN',
 'metformin',
 'Diaformin (1gm)',
 'DIABEX XR',
 'Diabex XR ER',
 'Glucophage']

In [111]:
values_to_drop_metforminnames = {'VE'}
metformin_matched_values = [x for x in metformin_matched_values if x not in values_to_drop_metforminnames]

In [112]:
metformin_all = med_utils.medication_all_timepoints(
    AIBL_df_selected, metformin_matched_values, medication_columns, selected_columns,
    id_col="id", visit_col="visit_no"
)
# metformin_all.to_csv("../preprocessed_data/AIBL/metformin_all_results_AIBL_missing.csv",index=False)

### control group
never have any of the 5 type of medications

In [113]:
drug_lists = [
    acei_matched_values,
    arb_matched_values,
    beta_blockers_matched_values,
    Ca_channel_blockers_matched_values,
    diuretics_matched_values,
    statin_matched_values,
    metformin_matched_values
]

all_target_drugs = set().union(*drug_lists)

In [114]:
row_has_target_drug = (
    AIBL_df_selected[medication_columns]
      .map(lambda x: med_utils.contains_any_medication_type(x, all_target_drugs))
      .any(axis=1)
)
ids_with_any_target_drug = AIBL_df_selected.loc[row_has_target_drug, 'id'].unique()
controls_df = AIBL_df_selected[~AIBL_df_selected['id'].isin(ids_with_any_target_drug)].copy()

In [115]:
controls_df["Has_Medication_This_Visit"] = False
controls_df = controls_df.drop(columns=[c for c in medication_columns if c in controls_df.columns])
# controls_df.to_csv("../preprocessed_data/AIBL/controls_df_AIBL_missing.csv",index=False)

### Adjust for the later modelling in R

In [116]:
datasets = {
    "ACEi": acei_all,
    "ARB": arb_all,
    "BetaBlk": beta_blockers_all,
    "CCB": Ca_channel_blockers_all,
    "Diuretic": diuretics_all,
    "Statin": statin_all,
    "Metformin": metformin_all,
    "Control": controls_df  
}

In [117]:
merged_df = med_utils.merge_medication_longitudinal(datasets, control_key="Control", extra_cols=["visit_no", "MMSE", "CDR"]+disease_columns_rename)

In [118]:
merged_df

,id,visit_date,status,age,sex,edu,APOE4,ACEi,ARB,BetaBlk,...,Diuretic,Statin,Metformin,Total_Meds,visit_no,MMSE,CDR,CVD,Endocrine,Psychiatric
0,2,2006-11-03,HC,65.30,0,16.0,0,False,False,False,...,False,False,False,0,1,29.0,0.0,False,False,False
1,2,2008-09-16,HC,67.17,0,16.0,0,False,False,False,...,False,False,False,0,2,30.0,0.0,False,False,<NA>
2,2,2010-03-24,HC,68.69,0,16.0,0,False,False,False,...,False,False,False,0,3,30.0,0.0,False,False,False
3,2,2011-09-16,HC,70.17,0,16.0,0,False,False,False,...,False,False,False,0,4,30.0,0.0,False,False,False
4,2,2013-04-11,HC,71.74,0,16.0,0,False,False,False,...,False,False,False,0,5,30.0,0.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9205,2999,2022-12-12,MCI,88.34,0,NaN,0,False,False,False,...,False,False,False,0,2,30.0,1.0,False,False,False
9206,3004,2023-03-16,MCI,70.84,0,NaN,0,False,False,False,...,False,False,False,0,2,22.0,1.0,False,False,True
9207,3014,2023-03-27,HC,67.61,0,NaN,0,False,False,False,...,False,False,False,0,2,30.0,0.0,True,True,False
9208,3029,2022-11-17,HC,70.26,0,NaN,0,False,False,False,...,False,False,False,0,2,30.0,0.0,True,False,False
9209,3030,2023-01-30,HC,68.96,1,NaN,0,False,False,False,...,False,False,False,0,2,30.0,0.0,True,True,False

In [119]:
med_cols = ['ACEi', 'ARB', 'BetaBlk', 'CCB', 'Diuretic', 'Statin', 'Metformin']
disease_cols = ['CVD', 'Endocrine', 'Psychiatric']

# participant never took ANY medication across ALL visits
med_control = (
    ~merged_df.groupby('id')[med_cols]
    .transform('any')
    .any(axis=1)
)

# participant never had ANY disease across ALL visits
disease_control = (
    ~merged_df.groupby('id')[disease_cols]
    .transform('any')
    .any(axis=1)
)

merged_df['Med_Control'] = med_control
merged_df['Disease_Control'] = disease_control
merged_df['Total_Disease'] = merged_df[disease_cols].sum(axis=1)

In [120]:
print(f"Initial rows: {len(merged_df)}")
merged_clean = merged_df.dropna(subset=['status'])
# merged_clean = merged_clean[~(merged_clean['MMSE'].isna() & merged_clean['CDR'].isna())]
merged_clean = merged_clean[~(merged_clean['CDR'].isna())]
print(f"After dropping missings: {len(merged_clean)}")
merged_clean = merged_clean[merged_clean.groupby('id')['visit_no'].transform('nunique') > 1]
print(f"After removing number of records: {len(merged_clean)}")

Initial rows: 9210
After dropping missings: 9182
After removing number of records: 8445

In [121]:
merged_clean = med_utils.clean_and_filter_participants(
    merged_clean,
    id_col='id',
    class_col ='status',
    time_col = 'visit_no',
    medication_ever_col=None,
    min_visits=2,
    if_print=True
)

Remaining participants: 1,708
Dropped participants:   0

In [122]:
### AIBL use the age informations,
merged_clean['months_since_baseline'] = (
    merged_clean.groupby('id')['age']
      .transform(lambda x: (x - x.min()) * 12)  # convert years to months
      .round()
      .astype(int)
)
merged_clean['year_since_baseline'] = (merged_clean['months_since_baseline']/ 12).round(2)

In [123]:
merged_clean = med_utils.clean_longitudinal(merged_clean)

In [124]:
(merged_clean.isna().mean()*100).sort_values(ascending=False).round(2)

edu                      22.26
Psychiatric               4.99
Endocrine                 4.55
CVD                       4.40
MMSE                      0.43
id                        0.00
Total_Meds                0.00
months_since_baseline     0.00
Total_Disease             0.00
Disease_Control           0.00
Med_Control               0.00
CDR                       0.00
visit_no                  0.00
Metformin                 0.00
visit_date                0.00
Statin                    0.00
Diuretic                  0.00
CCB                       0.00
BetaBlk                   0.00
ARB                       0.00
ACEi                      0.00
APOE4                     0.00
sex                       0.00
age                       0.00
status                    0.00
year_since_baseline       0.00
dtype: float64

In [125]:
med_result = merged_clean.groupby('id')[med_cols].nunique().eq(1)
med_summary = med_result.mean()
med_always_true = (merged_clean.groupby('id')[med_cols].sum() == merged_clean.groupby('id')[med_cols].count())
med_summary

ACEi         0.923888
ARB          0.853044
BetaBlk      0.923302
CCB          0.903981
Diuretic     0.959016
Statin       0.707845
Metformin    0.961944
dtype: float64

In [126]:
dis_result = merged_clean.groupby('id')[disease_cols].nunique().eq(1)
dis_summary = dis_result.mean()
dis_always_one = merged_clean.groupby('id')[disease_cols].min().eq(1)
dis_summary

CVD            0.725410
Endocrine      0.675059
Psychiatric    0.751171
dtype: float64

In [127]:
max_tab = merged_clean.groupby('id')['Total_Meds'].max().value_counts()
print("\nDistribution of max Total_Meds per participant:\n", max_tab)

Distribution of max Total_Meds per participant:
 Total_Meds
0    882
1    488
2    237
3     87
4     13
5      1
Name: count, dtype: int64

In [128]:
max_tab2 = merged_clean.groupby('id')['Total_Disease'].max().value_counts()
print("\nDistribution of max Total_Disease per participant:\n", max_tab2)

Distribution of max Total_Disease per participant:
 Total_Disease
1    644
2    633
0    272
3    159
Name: count, dtype: Int64

In [129]:
merged_clean.to_csv("../preprocessed_data/AIBL/AIBL_merge_full_missing.csv",index=False)

In [130]:
print(merged_clean['id'].nunique(), "unique participants in the final AIBL dataset.")

1708 unique participants in the final AIBL dataset.

In [131]:
# // PLEASE IGNORE BELOW. THIS IS JUST TO LOAD THE FINAL CLEANED DATASET FOR ANALYSIS, NOT THE PREPROCESSING STEPS.
# THE ONLY IMPUTED VARIABLE IS APOE4 WITH ONLY 2.2% MISSINGNESS, AND WE IMPUTED IT WITH NISSRANGER IN R.
# have the same function and result in Tables.Rmd
# merged_clean = pd.read_csv('../preprocessed_data/AIBL/AIBL_cdr_imputed.csv')

In [132]:
groups, labelled_df = med_utils.split_by_progression(merged_clean)

── Progression Group Summary ─────────────────────
AD_stable             :  247 participants |   801 rows
CU_MCI_progression    :  301 participants |  1546 rows
CU_stable             : 1019 participants |  5604 rows
MCI_reverter          :   34 participants |   182 rows
MCI_stable            :  107 participants |   312 rows
──────────────────────────────────────────────────

In [133]:
summary_df = med_utils.baseline_summary(labelled_df)
summary_df

                                 Measure         Value
0                 Age at baseline (year)    72.1 ± 7.3
1                        Gender (Female)   948 (55.5%)
2                       Education (year)    12.8 ± 3.1
3                            APOE4 (YES)   608 (35.6%)
4                        Visits (Record)    2.0 – 11.0
5            Follow up intervals (Month)   78.1 ± 50.4
6   Average medication taken at baseline     0.4 ± 0.7
7                              Stable CU  1019 (59.7%)
8                             Stable MCI    107 (6.3%)
9                     CU/MCI progression   301 (17.6%)
10                         MCI reversion     34 (2.0%)
11                           AD dementia   247 (14.5%)
12                      Mixed trajectory      0 (0.0%)
13                       ACEi prevalence     58 (3.4%)
14                        ARB prevalence    148 (8.7%)
15                    BetaBlk prevalence     44 (2.6%)
16                        CCB prevalence     92 (5.4%)
17                   Diuretic prevalence     30 (1.8%)
18                     Statin prevalence   354 (20.7%)
19                  Metformin prevalence     40 (2.3%)
20                        CVD prevalence   690 (40.4%)
21                  Endocrine prevalence   528 (30.9%)
22                Psychiatric prevalence   435 (25.5%)

In [134]:
med_cols_names = ["ACEi", "ARB", "BetaBlk", "CCB", "Diuretic", "Statin", "Metformin"]
med_utils.baseline_age_by_med(merged_clean, med_cols_names)

         drug      user     n   mean    sd       mean_sd  wald_chi2    wald_p
0        ACEi  non-user  1650  71.99  7.29  71.99 (7.29)   9.748389  0.001825
1        ACEi      user    58  75.02  6.51  75.02 (6.51)   9.748389  0.001825
2         ARB  non-user  1560  71.92  7.31  71.92 (7.31)  10.372825  0.001303
3         ARB      user   148  73.93  6.78  73.93 (6.78)  10.372825  0.001303
4     BetaBlk  non-user  1664  72.03  7.28  72.03 (7.28)   4.955839  0.026133
5     BetaBlk      user    44  74.50  7.40    74.5 (7.4)   4.955839  0.026133
6         CCB  non-user  1616  71.98  7.23  71.98 (7.23)   6.982873  0.008305
7         CCB      user    92  74.04  8.11  74.04 (8.11)   6.982873  0.008305
8    Diuretic  non-user  1678  72.03  7.28  72.03 (7.28)   7.174691  0.007465
9    Diuretic      user    30  75.62  7.20   75.62 (7.2)   7.174691  0.007465
10  Metformin  non-user  1668  72.04  7.29  72.04 (7.29)   3.402534  0.065270
11  Metformin      user    40  74.19  7.08  74.19 (7.08)   3.402534  0.065270
12     Statin  non-user  1354  71.74  7.17  71.74 (7.17)  15.205811  0.000100
13     Statin      user   354  73.43  7.60   73.43 (7.6)  15.205811  0.000100

In [135]:
med_utils.age_difference_by_med(merged_clean, med_cols_names)

        drug      mean_sd
0       ACEi  3.03 (7.27)
1        ARB  2.01 (7.27)
2    BetaBlk  2.48 (7.28)
3        CCB  2.06 (7.28)
4   Diuretic  3.59 (7.28)
5  Metformin  2.15 (7.28)
6     Statin  1.69 (7.26)

In [136]:
AIBL_df_selected

,id,visit_no,visit_date,status,age,sex,edu,APOE4,CDR,MMSE,...,Medical History.Heart Attack,Medical History.Stroke,Medical History.Diabetes,Medical History.Thyroid/Parathyroid Disease,Medical History.HighCholesterol,Medical History.Anxiety,Medical History.Depression,CVD,Endocrine,Psychiatric
0,2,1,2006-11-03,HC,65.30,0,16.0,0,0.0,29.0,...,False,False,False,False,<NA>,False,False,False,False,False
1,2,2,2008-09-16,HC,67.17,0,16.0,0,0.0,30.0,...,False,False,False,<NA>,<NA>,<NA>,<NA>,False,False,<NA>
2,2,3,2010-03-24,HC,68.69,0,16.0,0,0.0,30.0,...,False,False,False,False,<NA>,False,False,False,False,False
3,2,4,2011-09-16,HC,70.17,0,16.0,0,0.0,30.0,...,False,False,False,False,False,False,False,False,False,False
4,2,5,2013-04-11,HC,71.74,0,16.0,0,0.0,30.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9482,2999,2,2022-12-12,MCI,88.34,0,NaN,0,1.0,30.0,...,False,False,False,False,False,False,False,False,False,False
9483,3004,2,2023-03-16,MCI,70.84,0,NaN,0,1.0,22.0,...,False,False,False,False,False,True,True,False,False,True
9484,3014,2,2023-03-27,HC,67.61,0,NaN,0,0.0,30.0,...,False,False,False,False,True,False,False,True,True,False
9485,3029,2,2022-11-17,HC,70.26,0,NaN,0,0.0,30.0,...,False,False,False,False,False,False,False,True,False,False
9486,3030,2,2023-01-30,HC,68.96,1,NaN,0,0.0,30.0,...,False,False,True,False,True,False,False,True,True,False